services:
  app:
    build: ./app
    container_name: docker-day3-app
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: docker_day3
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: docker-day3-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: docker_day3
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: docker-day3-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
