// This file is generated by scripts/update-vitepress-routes.mjs.
// Do not edit it manually.

export const nav = [
  {
    "text": "首页",
    "link": "/"
  },
  {
    "text": "Python基础",
    "link": "/Python基础/"
  },
  {
    "text": "Node基础",
    "link": "/Node基础/"
  },
  {
    "text": "前端",
    "link": "/前端/webpack/"
  },
  {
    "text": "后端",
    "link": "/后端/数据库/"
  },
  {
    "text": "运维",
    "link": "/运维/docker/"
  },
  {
    "text": "CICD",
    "link": "/CICD/"
  }
]

export const sidebar = {
  "/Python基础/": [
    {
      "text": "Python基础",
      "items": [
        {
          "text": "总览",
          "link": "/Python基础/"
        },
        {
          "text": "Python 解包",
          "link": "/Python基础/解包.html"
        },
        {
          "text": "Python 数据类型与类",
          "link": "/Python基础/数据类型与类.html"
        },
        {
          "text": "Python 基础 Day1-Day5 总览",
          "link": "/Python基础/Day1-Day5总览.html"
        },
        {
          "text": "Python 与 JavaScript 对比",
          "link": "/Python基础/JavaScript对比.html"
        }
      ]
    },
    {
      "text": "Day1：基础语法与入门练习",
      "items": [
        {
          "text": "Day1",
          "link": "/Python基础/day1/"
        },
        {
          "text": "练习题",
          "link": "/Python基础/day1/练习题.html"
        }
      ]
    },
    {
      "text": "Day2：Python 速通（JavaScript 基础版）",
      "items": [
        {
          "text": "Day2",
          "link": "/Python基础/day2/"
        },
        {
          "text": "练习题",
          "link": "/Python基础/day2/练习题.html"
        }
      ]
    },
    {
      "text": "Day3：类与对象",
      "items": [
        {
          "text": "Day3",
          "link": "/Python基础/day3/"
        },
        {
          "text": "Day3 进阶：继承与类的拓展",
          "link": "/Python基础/day3/进阶.html"
        },
        {
          "text": "练习题",
          "link": "/Python基础/day3/练习题.html"
        }
      ]
    },
    {
      "text": "Day4：函数进阶与异常处理",
      "items": [
        {
          "text": "Day4",
          "link": "/Python基础/day4/"
        },
        {
          "text": "练习题",
          "link": "/Python基础/day4/练习题.html"
        }
      ]
    },
    {
      "text": "Day5：文件读写、JSON 与 CSV",
      "items": [
        {
          "text": "Day5",
          "link": "/Python基础/day5/"
        },
        {
          "text": "练习题",
          "link": "/Python基础/day5/练习题.html"
        }
      ]
    }
  ],
  "/Node基础/": [
    {
      "text": "Node基础",
      "items": [
        {
          "text": "总览",
          "link": "/Node基础/"
        }
      ]
    },
    {
      "text": "Day1：Node 环境、npm 与模块系统",
      "items": [
        {
          "text": "Day1",
          "link": "/Node基础/day1/"
        },
        {
          "text": "练习题",
          "link": "/Node基础/day1/练习题.html"
        }
      ]
    },
    {
      "text": "Day2：路径、文件系统与命令行脚本",
      "items": [
        {
          "text": "Day2",
          "link": "/Node基础/day2/"
        },
        {
          "text": "练习题",
          "link": "/Node基础/day2/练习题.html"
        }
      ]
    }
  ],
  "/前端/": [
    {
      "text": "Webpack 入门到静态资源指南",
      "items": [
        {
          "text": "总览",
          "link": "/前端/webpack/"
        },
        {
          "text": "Day2",
          "link": "/前端/webpack/day2/"
        },
        {
          "text": "Day3",
          "link": "/前端/webpack/day3/"
        },
        {
          "text": "练习题",
          "link": "/前端/webpack/day2/练习题.html"
        },
        {
          "text": "练习题",
          "link": "/前端/webpack/day3/练习题.html"
        },
        {
          "text": "webpack个人总结",
          "link": "/前端/webpack/个人总结.html"
        }
      ]
    },
    {
      "text": "Angular 12 到 Angular 22 特性演进指南",
      "items": [
        {
          "text": "总览",
          "link": "/前端/angular/"
        },
        {
          "text": "Day1",
          "link": "/前端/angular/day1/"
        }
      ]
    },
    {
      "text": "leaflet轻量开源的2D地图渲染引擎",
      "items": [
        {
          "text": "总览",
          "link": "/前端/leaflet/"
        }
      ]
    }
  ],
  "/后端/": [
    {
      "text": "MySQL 学习指南",
      "items": [
        {
          "text": "总览",
          "link": "/后端/数据库/"
        },
        {
          "text": "Day1",
          "link": "/后端/数据库/day1/"
        },
        {
          "text": "Day2",
          "link": "/后端/数据库/day2/"
        },
        {
          "text": "Day3",
          "link": "/后端/数据库/day3/"
        },
        {
          "text": "练习答案",
          "link": "/后端/数据库/day1/答案.html"
        },
        {
          "text": "练习题",
          "link": "/后端/数据库/day1/练习题.html"
        },
        {
          "text": "练习题",
          "link": "/后端/数据库/day2/练习题.html"
        },
        {
          "text": "练习题",
          "link": "/后端/数据库/day3/练习题.html"
        },
        {
          "text": "MySQL 知识点总结",
          "link": "/后端/数据库/总结.html"
        }
      ]
    }
  ],
  "/运维/": [
    {
      "text": "Docker 学习指南",
      "items": [
        {
          "text": "总览",
          "link": "/运维/docker/"
        },
        {
          "text": "Day1",
          "link": "/运维/docker/day1/"
        },
        {
          "text": "Day2",
          "link": "/运维/docker/day2/"
        },
        {
          "text": "Day3",
          "link": "/运维/docker/day3/"
        },
        {
          "text": "练习题",
          "link": "/运维/docker/day1/练习题.html"
        },
        {
          "text": "命令示例",
          "link": "/运维/docker/day1/命令示例.html"
        },
        {
          "text": "练习题",
          "link": "/运维/docker/day2/练习题.html"
        },
        {
          "text": "练习题",
          "link": "/运维/docker/day3/练习题.html"
        }
      ]
    }
  ],
  "/CICD/": [
    {
      "text": "CICD",
      "items": [
        {
          "text": "总览",
          "link": "/CICD/"
        }
      ]
    },
    {
      "text": "Day1：GitHub Actions 基础与第一个 CI",
      "items": [
        {
          "text": "Day1",
          "link": "/CICD/day1/"
        },
        {
          "text": "练习题",
          "link": "/CICD/day1/练习题.html"
        }
      ]
    },
    {
      "text": "Day2：Node 项目 CI、缓存与构建产物",
      "items": [
        {
          "text": "Day2",
          "link": "/CICD/day2/"
        },
        {
          "text": "练习题",
          "link": "/CICD/day2/练习题.html"
        }
      ]
    },
    {
      "text": "Day3：部署、Secrets 与环境保护",
      "items": [
        {
          "text": "Day3",
          "link": "/CICD/day3/"
        },
        {
          "text": "练习题",
          "link": "/CICD/day3/练习题.html"
        }
      ]
    }
  ],
  "/": [
    {
      "text": "学习入口",
      "items": [
        {
          "text": "首页",
          "link": "/"
        },
        {
          "text": "Python 基础入门",
          "link": "/Python基础/"
        },
        {
          "text": "Node 基础查漏补缺",
          "link": "/Node基础/"
        },
        {
          "text": "Webpack 入门到静态资源指南",
          "link": "/前端/webpack/"
        },
        {
          "text": "MySQL 学习指南",
          "link": "/后端/数据库/"
        },
        {
          "text": "Docker 学习指南",
          "link": "/运维/docker/"
        },
        {
          "text": "GitHub Actions CI/CD 学习指南",
          "link": "/CICD/"
        }
      ]
    }
  ]
}
